#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 0 ]]; then
  echo "Usage: $0" >&2
  exit 2
fi

sdk=$(cd "$(dirname "$0")/.." && pwd)
root="$sdk/project/realtek_amebaD_va0_example/GCC-RELEASE"
[[ -f "$root/project_lp/Makefile" && -f "$root/project_hp/Makefile" ]] || {
  echo "Not the expected GW018-DM SDK checkout: $root" >&2; exit 1;
}
ota_config="$sdk/component/common/example/ota_http/gw018_ota_config.h"
[[ -f "$ota_config" ]] || {
  echo "OTA host is not configured; run tools/configure-ota-host.py HOST first." >&2; exit 1;
}
grep -q 'GW018_OTA_CONFIG_GENERATED' "$ota_config" || {
  echo "OTA config is not generated by tools/configure-ota-host.py; refusing to build." >&2; exit 1;
}
grep -q '"ota.example.invalid"' "$ota_config" && {
  echo "OTA host is still the documentation placeholder; configure a reachable host first." >&2; exit 1;
}

for command in make curl tar sha256sum; do
  command -v "$command" >/dev/null || { echo "Missing required command: $command" >&2; exit 1; }
done

archive="$root/project_hp/toolchain/asdk/asdk-6.4.1-linux-newlib-build-2773-i686.tar.bz2"
expected=eeaef0c05f842bd50166158df166150fecb84b4137141e79427e4d32b45153bc
url=https://files.seeedstudio.com/arduino/tools/arm-none-eabi/asdk-6.4.1-linux-newlib-build-2773-i686.tar.bz2
mkdir -p "$(dirname "$archive")"
if [[ ! -f "$archive" ]]; then
  echo "Downloading pinned ARM toolchain archive (~250 MB) from Seeed..."
  curl --fail --location --retry 3 "$url" --output "$archive.tmp"
  mv "$archive.tmp" "$archive"
fi
actual=$(sha256sum "$archive" | awk '{print $1}')
if [[ "$actual" != "$expected" ]]; then
  echo "Toolchain SHA-256 mismatch; refusing to build." >&2
  exit 1
fi

# The upstream tree tracks several directly-invoked helpers without executable
# mode. Temporarily add it for this build, then restore the original modes.
temporary_exec=()
archive_lib="$root/project_hp/asdk/lib/application/lib_user.a"
archive_backup=""
if [[ -f "$archive_lib" ]]; then
  archive_backup=$(mktemp)
  cp -p "$archive_lib" "$archive_backup"
fi
while IFS= read -r -d '' file; do
  if [[ ! -x "$file" ]]; then
    chmod u+x "$file"
    temporary_exec+=("$file")
  fi
done < <(find "$root/project_lp" "$root/project_hp" -type f \( -name '*.sh' -o -name checksum \) -print0)
restore_modes() {
  for file in "${temporary_exec[@]}"; do chmod u-x "$file"; done
  if [[ -n "$archive_backup" ]]; then
    cp -p "$archive_backup" "$archive_lib"
    rm -f "$archive_backup"
  fi
}
trap restore_modes EXIT

compat="$(cd "$(dirname "$0")/compat" && pwd)"
echo "Building low-power (KM0) and high-power (KM4) firmware..."
build_log=$(mktemp)
if ! PATH="$compat:$PATH" make -C "$root/project_lp" all >"$build_log" 2>&1; then
  tail -n 100 "$build_log" >&2
  exit 1
fi
if ! PATH="$compat:$PATH" make -C "$root/project_hp" all >>"$build_log" 2>&1; then
  tail -n 100 "$build_log" >&2
  exit 1
fi
tail -n 30 "$build_log"
rm -f "$build_log"

for artifact in \
  "$root/project_lp/asdk/image/km0_boot_all.bin" \
  "$root/project_hp/asdk/image/km4_boot_all.bin" \
  "$root/project_hp/asdk/image/km0_km4_image2.bin" \
  "$root/project_hp/asdk/image/OTA_All.bin"; do
  [[ -s "$artifact" ]] || { echo "Expected build artifact missing: $artifact" >&2; exit 1; }
  sha256sum "$artifact"
done
echo "Build complete. See README.md for UART first-flash and OTA update procedures."
